highlighter: pygments

markdown: redcarpet

kramdown:
  input: GFM

redcarpet:
  extensions: [autolink, no_intra_emphasis, strikethrough, tables, with_toc_data]

sass:
    style: :compressed

timezone: Asia/Shanghai
