encoding: UTF-8
future: true
gfm_quirks: paragraph_end
github: [metadata]
jailed: false
kramdown:
  input: GFM
  hard_wrap: false
paginate: 8
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
sass:
  style: :compressed

title: Daniel Zhou's Chaos
author: Daniel Zhou
lang: en_GB
url: nerddan.github.io
social:
  name: Daniel Zhou
  links:
    - https://douban.com/people/danielc
    - https://github.com/nerdDan
    - https://linkedin.com/in/danichau
    - https://quora.com/Daniel-Chau-3
    - https://twitter.com/nerdDaniel
