# https://jekyllrb.com/docs/configuration/
# https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll

encoding: UTF-8
future: true
gfm_quirks: paragraph_end
github: [metadata]
jailed: false
kramdown:
  input: GFM
  hard_wrap: false
paginate: 8
paginate_path: "/archive/:num"
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
sass:
  style: :compressed

title: Daniel Zhou's Chaos
author: Daniel Zhou
lang: en_GB
url: nerddan.github.io
